### ISSUE TITLE
Time rollover is handled incorrectly 

### ISSUE THREAD

**Issue by harbingerftw** [EltonChou/EorzeaEnv#14]
While trying to calculate some windows where the time, moon phase and weather all matched (for an S rank) I discovered that the windows returned were incomplete (when compared to other tools).

After further testing I found that the provided `weather_period` generator was returning 24, 16, and 8. When 24 is set as the bell in `EorzeaTime` it does not calculate the expected moon phase that would match the time and weather causing incorrect results. Now I am not an expert in time libraries (and do not wish to be) but 24 is an invalid hour (or bell in this case). 

The source is that the [`bell` setter allows 24](https://github.com/EltonChou/EorzeaEnv/blob/34e623e8a5d4bc188381db6a12f59608a0517ac9/EorzeaEnv/eorzea_time.py#L109) and the [`minute` setter allows 60](https://github.com/EltonChou/EorzeaEnv/blob/34e623e8a5d4bc188381db6a12f59608a0517ac9/EorzeaEnv/eorzea_time.py#L124), both should be `>=` instead of `>`. I would have submitted a PR but I was just going to make an issue to check if I was maybe missing something.

**Comment by EltonChou** [comment]
Yes, they should be `>=`. 
This is my mistake.  
[Ref](https://github.com/Rogueadyn/SaintCoinach/blob/f969b441584688c02dde2fadac548c4a5aaa3faa/SaintCoinach/EorzeaDateTime.cs)

You can submit a PR if you want.
It would be helpful if you can add some test cases about this issue.
