### ISSUE TITLE
[Recommend] Add CN server Data

### ISSUE THREAD

**Issue by CodeZWT** [EltonChou/EorzeaEnv#6]
Hello,
     I'am a ffxiv player form cn server, can i ask you add CN server data into EorzeaEnv,please
     If you need the client，there have csv data by [SaintCoinach]，
            `https://github.com/thewakingsands/ffxiv-datamining-cn`
     but the CN server have some different with JP&EN server，when JP sever in 6.2 Patch，CN sever is in 6.1 Patch
     I hope i can receive reply, thanks
     have a good day

**Comment by EltonChou** [comment]
Thanks for you suggestion and information.
I think this could be resolved quickly since the data structures are almost same.
I will port them to the package at next release.

**Comment by EltonChou** [comment]
@CodeZWT 
New version has been pushed to the pypi. You can update your pacakge now.
Also, feel free to open issue when the CN server bump the version.

**Comment by CodeZWT** [comment]
Thank you for your assistance,I will update new version soon
